<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">registerMetrics</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCWlmY25hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNv
ciwgImlmY25hbWUiICk7ClN0cmluZwlzdmNuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlw
ZWxpbmVDdXJzb3IsICJzdmNuYW1lIiApOwpTdHJpbmcJbWV0cmljc1NlcnZpY2VGcW4gPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgIm1ldHJpY3NTZXJ2aWNlRnFuIiApOwpw
aXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgppZiggKGlmY25hbWUgPT0gbnVsbCB8fCAiIi5lcXVh
bHMoaWZjbmFtZSkgfHwgc3ZjbmFtZSA9PSBudWxsIHx8ICIiLmVxdWFscyhzdmNuYW1lKSApICYm
IChtZXRyaWNzU2VydmljZUZxbiA9PSBudWxsIHx8ICIiLmVxdWFscyhtZXRyaWNzU2VydmljZUZx
bikgKSkgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlByb3ZpZGUgdGhlIGZvbGRlciBh
bmQgc2VydmljZSBuYW1lIGZvciB0aGUgc2VydmljZSBpbXBsZW1lbnRpbmcgdGhlIHd4LnByb21l
dGhldXMucHViLmRvY3VtZW50czpwcm9tZXRoZXVzTWV0cmljIHNwZWNpZmljYXRpb24iKTsKfQoK
aWYoIG1ldHJpY3NTZXJ2aWNlRnFuICE9IG51bGwgJiYgISIiLmVxdWFscyhtZXRyaWNzU2Vydmlj
ZUZxbikgJiYgbWV0cmljc1NlcnZpY2VGcW4uY29udGFpbnMoIjoiKSApIHsKCVN0cmluZ1tdIHNl
cnZpY2UgPSBtZXRyaWNzU2VydmljZUZxbi5zcGxpdCgiOiIpOwoJaWZjbmFtZSA9IHNlcnZpY2Vb
MF07CglzdmNuYW1lID0gc2VydmljZVsxXTsKfQplbHNlIGlmIChpZmNuYW1lICE9IG51bGwgJiYg
ISIiLmVxdWFscyhpZmNuYW1lKSAmJiBzdmNuYW1lICE9IG51bGwgJiYgISIiLmVxdWFscyhzdmNu
YW1lKSl7CgltZXRyaWNzU2VydmljZUZxbiA9IGlmY25hbWUgKyAiOiIgKyBzdmNuYW1lOwp9CmVs
c2V7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiUHJvdmlkZSBmb2xkZXIgYW5kIHNlcnZp
Y2VuYW1lIGFzIGlmY25hbWUgYW5kIHN2Y25hbWUgT1IgYXMgbWV0cmljc1NlcnZpY2VGcW4sIHNl
cGVyYXRlZCBieSAnOiciKTsKfQpsb2dnZXIuZGVidWcoIkFkZGVkIHNlcnZpY2UgIiArIGlmY25h
bWUgKyAiOiIgKyBzdmNuYW1lICsgIiB0byBsaXN0IG9mIHJlZ2lzdGVyZWQgbWV0cmljcyBzZXJp
dmNlcy4iKTsKaWYgKCFyZWdpc3RlcmVkTWV0cmljcy5jb250YWluc0tleShtZXRyaWNzU2Vydmlj
ZUZxbikpewoJcmVnaXN0ZXJlZE1ldHJpY3MucHV0KG1ldHJpY3NTZXJ2aWNlRnFuLCBuZXcgU3Ry
aW5nW10ge2lmY25hbWUsIHN2Y25hbWV9KTsKfQ==</value>
</Values>
