<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">registerMetrics</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional ifcname</value>
    <value>[i] field:0:optional svcname</value>
    <value>[i] field:0:optional metricsServiceFqn</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCWlmY25hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNv
ciwgImlmY25hbWUiICk7ClN0cmluZwlzdmNuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlw
ZWxpbmVDdXJzb3IsICJzdmNuYW1lIiApOwpTdHJpbmcJbWV0cmljc1NlcnZpY2VGcW4gPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgIm1ldHJpY3NTZXJ2aWNlRnFuIiApOwpw
aXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgppZiggKGlmY25hbWUgPT0gbnVsbCB8fCAiIi5lcXVh
bHMoaWZjbmFtZSkgfHwgc3ZjbmFtZSA9PSBudWxsIHx8ICIiLmVxdWFscyhzdmNuYW1lKSApICYm
IChtZXRyaWNzU2VydmljZUZxbiA9PSBudWxsIHx8ICIiLmVxdWFscyhtZXRyaWNzU2VydmljZUZx
bikgKSkgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlByb3ZpZGUgdGhlIGZvbGRlciBh
bmQgc2VydmljZSBuYW1lIGZvciB0aGUgc2VydmljZSBpbXBsZW1lbnRpbmcgdGhlIHd4LnByb21l
dGhldXMucHViLmRvY3VtZW50czpwcm9tZXRoZXVzTWV0cmljIHNwZWNpZmljYXRpb24iKTsKfQoK
aWYoIG1ldHJpY3NTZXJ2aWNlRnFuICE9IG51bGwgJiYgISIiLmVxdWFscyhtZXRyaWNzU2Vydmlj
ZUZxbikgJiYgbWV0cmljc1NlcnZpY2VGcW4uY29udGFpbnMoIjoiKSApIHsKCVN0cmluZ1tdIHNl
cnZpY2UgPSBtZXRyaWNzU2VydmljZUZxbi5zcGxpdCgiOiIpOwoJaWZjbmFtZSA9IHNlcnZpY2Vb
MF07CglzdmNuYW1lID0gc2VydmljZVsxXTsKfQpKb3VybmFsTG9nZ2VyLmxvZyg0LCAgSm91cm5h
bExvZ2dlci5GQUNfRkxPV19TVkMsIEpvdXJuYWxMb2dnZXIuREVCVUcsICJ3eC5wcm9tZXRoZXVz
IiwgIkFkZGVkIHNlcnZpY2UgIiArIGlmY25hbWUgKyAiOiIgKyBzdmNuYW1lICsgIiB0byB0aGUg
bGlzdCBvZiByZWdpc3RlcmVkIG1ldHJpY3Mgc2VydmljZXMuIiApOwpyZWdpc3RlcmVkTWV0cmlj
cy5wdXQobWV0cmljc1NlcnZpY2VGcW4sIG5ldyBTdHJpbmdbXSB7aWZjbmFtZSwgc3ZjbmFtZX0p
OwoJCgkK</value>
</Values>
