<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">metricToText</value>
  <array name="sig" type="value" depth="1">
    <value>[i] recref:1:required metricsPrometheus wx.prometheus.pub.documents:text</value>
    <value>[i] field:1:optional textMetricsString</value>
    <value>[i] object:1:required metricsBytes</value>
    <value>[o] field:0:required text</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCi8vIG1ldHJpY3MKSURhdGFbXQkJbWV0cmljc1Byb21ldGhldXMgPSBJRGF0YVV0aWwu
Z2V0SURhdGFBcnJheSggcGlwZWxpbmVDdXJzb3IsICJtZXRyaWNzUHJvbWV0aGV1cyIgKTsKU3Ry
aW5nW10JdGV4dE1ldHJpY3NTdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nQXJyYXkoIHBpcGVs
aW5lQ3Vyc29yLCAidGV4dE1ldHJpY3NTdHJpbmciICk7Ck9iamVjdFtdCW1ldHJpY3NCeXRlcyA9
IElEYXRhVXRpbC5nZXRPYmplY3RBcnJheSggcGlwZWxpbmVDdXJzb3IsICJtZXRyaWNzQnl0ZXMi
ICk7CgpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgppZiAoIChtZXRyaWNzUHJvbWV0aGV1cyA9
PSBudWxsKSAmJiAodGV4dE1ldHJpY3NTdHJpbmcgPT0gbnVsbCkgJiYgKG1ldHJpY3NCeXRlcyA9
PSBudWxsKSkgewoJcmV0dXJuOwp9ClN0cmluZ0J1aWxkZXIgdGV4dCA9IG5ldyBTdHJpbmdCdWls
ZGVyKCk7CmlmIChtZXRyaWNzUHJvbWV0aGV1cyAhPSBudWxsKSB7Cglmb3IgKCBpbnQgaSA9IDA7
IGkgPCBtZXRyaWNzUHJvbWV0aGV1cy5sZW5ndGg7IGkrKyApIHsKCQlJRGF0YUN1cnNvciBtZXRy
aWNzUHJvbWV0aGV1c0N1cnNvciA9IG1ldHJpY3NQcm9tZXRoZXVzW2ldLmdldEN1cnNvcigpOwoJ
CVN0cmluZyAgSEVMUCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIG1ldHJpY3NQcm9tZXRoZXVzQ3Vy
c29yLCAiSEVMUCIgKTsKICAgICAgICBTdHJpbmcgIFRZUEUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBtZXRyaWNzUHJvbWV0aGV1c0N1cnNvciwgIlRZUEUiICk7CQoJCUlEYXRhW10gbWV0cmljcyA9
IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KG1ldHJpY3NQcm9tZXRoZXVzQ3Vyc29yLCAibWV0cmlj
cyIpOwoJCUlEYXRhW10gcmVjb3JkcyA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KG1ldHJpY3NQ
cm9tZXRoZXVzQ3Vyc29yLCAicmVjb3JkcyIpOwoJCW1ldHJpY3NQcm9tZXRoZXVzQ3Vyc29yLmRl
c3Ryb3koKTsKCQlpZiAocmVjb3JkcyA9PSBudWxsICYmIG1ldHJpY3MgPT0gbnVsbCkgewoJCQlj
b250aW51ZTsKCQl9CgkJaWYgKCBtZXRyaWNzICE9IG51bGwgKSB7CQoJCQl0ZXh0LmFwcGVuZChn
ZXRMZWdhY3lNZXRyaWNzKFRZUEUsIEhFTFAsIG1ldHJpY3MpKTsKCQl9CgkJaWYgKCByZWNvcmRz
ICE9IG51bGwgKSB7CQoJCQl0ZXh0LmFwcGVuZChnZXRNZXRyaWNzKHJlY29yZHMpKTsJCQoJCX0K
CX0KfQppZiAodGV4dE1ldHJpY3NTdHJpbmcgIT0gbnVsbCkgewoJZm9yICggaW50IGlfMiA9IDA7
IGlfMiA8IHRleHRNZXRyaWNzU3RyaW5nLmxlbmd0aDsgaV8yKysgKSB7CgkJdGV4dC5hcHBlbmQo
dGV4dE1ldHJpY3NTdHJpbmdbaV8yXSk7Cgl9Cn0KaWYgKG1ldHJpY3NCeXRlcyAhPSBudWxsKSB7
Cglmb3IgKCBpbnQgaV8zID0gMDsgaV8zIDwgbWV0cmljc0J5dGVzLmxlbmd0aDsgaV8zKysgKSB7
CgkJdGV4dC5hcHBlbmQobmV3IFN0cmluZygoKGJ5dGVbXSltZXRyaWNzQnl0ZXNbaV8zXSkpKTsK
CX0KfQppZiggdGV4dC5sZW5ndGgoKSA9PSAwICkgewoJdGV4dC5hcHBlbmQoIiMgV3hQcm9tZXRo
ZXVzIGdvdCBub3RoaW5nIGZvciB5b3UgcmlnaHQgbm93Li4uIik7Cn0KCi8vIHBpcGVsaW5lCklE
YXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInRleHQiLCB0ZXh0LnRvU3RyaW5nKCkgKTsKcGlw
ZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7CgkK</value>
</Values>
