<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">unregisterMetrics</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJaWZjbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vy
c29yLCAiaWZjbmFtZSIgKTsNClN0cmluZwlzdmNuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZygg
cGlwZWxpbmVDdXJzb3IsICJzdmNuYW1lIiApOw0KU3RyaW5nCW1ldHJpY3NTZXJ2aWNlRnFuID0g
SURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJtZXRyaWNzU2VydmljZUZxbiIg
KTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KaWYoIChpZmNuYW1lID09IG51bGwgfHwg
IiIuZXF1YWxzKGlmY25hbWUpIHx8IHN2Y25hbWUgPT0gbnVsbCB8fCAiIi5lcXVhbHMoc3ZjbmFt
ZSkgKSAmJiAobWV0cmljc1NlcnZpY2VGcW4gPT0gbnVsbCB8fCAiIi5lcXVhbHMobWV0cmljc1Nl
cnZpY2VGcW4pICkpIHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiUHJvdmlkZSB0aGUg
Zm9sZGVyIGFuZCBzZXJ2aWNlIG5hbWUgZm9yIHRoZSBzZXJ2aWNlIGltcGxlbWVudGluZyB0aGUg
d3gucHJvbWV0aGV1cy5wdWIuZG9jdW1lbnRzOnByb21ldGhldXNNZXRyaWMgc3BlY2lmaWNhdGlv
biIpOw0KfQ0KDQppZiggbWV0cmljc1NlcnZpY2VGcW4gPT0gbnVsbCB8fCAiIi5lcXVhbHMobWV0
cmljc1NlcnZpY2VGcW4pICkgew0KCW1ldHJpY3NTZXJ2aWNlRnFuID0gaWZjbmFtZSArICI6IiAr
IHN2Y25hbWU7DQp9DQoNCmxvZ2dlci5kZWJ1ZygiUmVtb3ZlZCBzZXJ2aWNlICIgKyBtZXRyaWNz
U2VydmljZUZxbiArICIgZnJvbSB0aGUgbGlzdCBvZiByZWdpc3RlcmVkIG1ldHJpY3Mgc2Vydmlj
ZXMuIik7DQppZiAobWV0cmljc1NlcnZpY2VGcW4gIT0gbnVsbCkgcmVnaXN0ZXJlZE1ldHJpY3Mu
cmVtb3ZlKG1ldHJpY3NTZXJ2aWNlRnFuKTs=</value>
</Values>
