<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">logMessage</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required logMessage</value>
    <value>[i] field:0:required severity {"TRACE","DEBUG","INFO","WARN","ERROR","FATAL"}</value>
    <value>[i] field:0:optional logger</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nCWxvZ01lc3NhZ2UgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgImxvZ01lc3NhZ2UiICk7ClN0cmluZwlzZXZlcml0eSA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAic2V2ZXJpdHkiICk7ClN0cmluZyBsb2dnZXIgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImxvZ2dlciIgKTsKU3RyaW5nIHByZWZpeCA9
IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAicHJlZml4IiApOwpwaXBlbGlu
ZUN1cnNvci5kZXN0cm95KCk7CgppZiAoIGxvZ2dlciA9PSBudWxsICkgewoJcHJlZml4ID0gInd4
LnByb21ldGhldXMiOwp9CmlmICggcHJlZml4ICE9IG51bGwgKSB7CglwcmVmaXggPSBsb2dnZXIg
KyAiLiIgKyBwcmVmaXg7Cn0KZWxzZSB7CglwcmVmaXggPSBsb2dnZXI7Cn0KCmlmKCBzZXZlcml0
eS5lcXVhbHNJZ25vcmVDYXNlKCJ3YXJuIikgKSB7CglKb3VybmFsTG9nZ2VyLmxvZyg0LCAgSm91
cm5hbExvZ2dlci5GQUNfRkxPV19TVkMsIEpvdXJuYWxMb2dnZXIuV0FSTklORywgcHJlZml4LCBs
b2dNZXNzYWdlICk7Cn0gZWxzZSBpZiggc2V2ZXJpdHkuZXF1YWxzSWdub3JlQ2FzZSgiZXJyb3Ii
KSApIHsKCUpvdXJuYWxMb2dnZXIubG9nKDQsICBKb3VybmFsTG9nZ2VyLkZBQ19GTE9XX1NWQywg
Sm91cm5hbExvZ2dlci5FUlJPUiwgcHJlZml4LCBsb2dNZXNzYWdlICk7Cn0gZWxzZSBpZiggc2V2
ZXJpdHkuZXF1YWxzSWdub3JlQ2FzZSgiZmF0YWwiKSApIHsKCUpvdXJuYWxMb2dnZXIubG9nKDQs
ICBKb3VybmFsTG9nZ2VyLkZBQ19GTE9XX1NWQywgSm91cm5hbExvZ2dlci5DUklUSUNBTCwgcHJl
Zml4LCBsb2dNZXNzYWdlICk7Cn0gZWxzZSBpZiggc2V2ZXJpdHkuZXF1YWxzSWdub3JlQ2FzZSgi
aW5mbyIpICkgewoJSm91cm5hbExvZ2dlci5sb2coNCwgIEpvdXJuYWxMb2dnZXIuRkFDX0ZMT1df
U1ZDLCBKb3VybmFsTG9nZ2VyLklORk8sIHByZWZpeCwgbG9nTWVzc2FnZSApOwp9IGVsc2UgaWYo
IHNldmVyaXR5LmVxdWFsc0lnbm9yZUNhc2UoImRlYnVnIikgKSB7CglKb3VybmFsTG9nZ2VyLmxv
Zyg0LCAgSm91cm5hbExvZ2dlci5GQUNfRkxPV19TVkMsIEpvdXJuYWxMb2dnZXIuREVCVUcsIHBy
ZWZpeCwgbG9nTWVzc2FnZSApOwp9IGVsc2UgewoJSm91cm5hbExvZ2dlci5sb2coNCwgIEpvdXJu
YWxMb2dnZXIuRkFDX0ZMT1dfU1ZDLCBKb3VybmFsTG9nZ2VyLlRSQUNFLCBwcmVmaXgsIGxvZ01l
c3NhZ2UgKTsKfQoJCg==</value>
</Values>
