<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">loadPrometheusConfigForPackage</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required packageName</value>
    <value>[o] recref:0:required packageConfig wx.prometheus.impl.documents:packageConfig</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKU3RyaW5nIHBhY2thZ2VOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1
cnNvciwgInBhY2thZ2VOYW1lIik7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCmlmIChwYWNr
YWdlTmFtZSA9PSBudWxsKSB7CglyZXR1cm47Cn0KRmlsZSBjb25maWdEaXIgPSBTZXJ2ZXJBUEku
Z2V0UGFja2FnZUNvbmZpZ0RpcihwYWNrYWdlTmFtZSk7CmlmICghY29uZmlnRGlyLmV4aXN0cygp
KSB7CglyZXR1cm47Cn0KU3RyaW5nW10gY29uZmlnRmlsZXMgPSBjb25maWdEaXIubGlzdChuZXcg
RmlsZW5hbWVGaWx0ZXIoKSB7CglAT3ZlcnJpZGUKCXB1YmxpYyBib29sZWFuIGFjY2VwdChGaWxl
IHBhcmFtRmlsZSwgU3RyaW5nIHBhcmFtU3RyaW5nKSB7CgkJcmV0dXJuIHBhcmFtU3RyaW5nLmVx
dWFsc0lnbm9yZUNhc2UoQ09ORklHX0ZJTEVfTkFNRSk7Cgl9Cn0pOwpmb3IgKFN0cmluZyBjb25m
aWdGaWxlTmFtZSA6IGNvbmZpZ0ZpbGVzKSB7CglGaWxlIGNvbmZpZ0ZpbGUgPSBuZXcgRmlsZShj
b25maWdEaXIsIGNvbmZpZ0ZpbGVOYW1lKTsKCVByb3BlcnRpZXMgcHJvcHMgPSBuZXcgUHJvcGVy
dGllcygpOwoJdHJ5IHsKCQlwcm9wcy5sb2FkKG5ldyBGaWxlSW5wdXRTdHJlYW0oY29uZmlnRmls
ZSkpOwoJCUpvdXJuYWxMb2dnZXIubG9nKDQsICBKb3VybmFsTG9nZ2VyLkZBQ19GTE9XX1NWQywg
Sm91cm5hbExvZ2dlci5JTkZPLCAid3gucHJvbWV0aGV1cy5jb25maWciLCAiRm91bmQgIiArIENP
TkZJR19GSUxFX05BTUUgKyAiIGZpbGUgaW4gY29uZmlnIGRpciBmb3IgcGFja2FnZSAiICsgcGFj
a2FnZU5hbWUgKTsKCQlTdHJpbmcgcmVnaXN0ZXJGb3JQcm9tZXRoZXVzID0gIHByb3BzLmdldFBy
b3BlcnR5KCJyZWdpc3RlckZvclByb21ldGhldXMiLCAiZmFsc2UiKTsKCQlpZiggISJ0cnVlIi5l
cXVhbHMocmVnaXN0ZXJGb3JQcm9tZXRoZXVzKSApIHsKCQkJcmVnaXN0ZXJGb3JQcm9tZXRoZXVz
ID0gImZhbHNlIjsKCQl9CgkJU3RyaW5nIG1ldHJpY3NTZXJ2aWNlRnFuID0gIHByb3BzLmdldFBy
b3BlcnR5KCJtZXRyaWNzU2VydmljZUZxbiIpOwoJCQoJCUlEYXRhCXBhY2thZ2VDb25maWcgPSBJ
RGF0YUZhY3RvcnkuY3JlYXRlKCk7CgkJSURhdGFDdXJzb3IgcGFja2FnZUNvbmZpZ0N1cnNvciA9
IHBhY2thZ2VDb25maWcuZ2V0Q3Vyc29yKCk7CgkJSURhdGFVdGlsLnB1dCggcGFja2FnZUNvbmZp
Z0N1cnNvciwgInJlZ2lzdGVyRm9yUHJvbWV0aGV1cyIsIHJlZ2lzdGVyRm9yUHJvbWV0aGV1cyAp
OwoJCUlEYXRhVXRpbC5wdXQoIHBhY2thZ2VDb25maWdDdXJzb3IsICJwYWNrYWdlTmFtZSIsIHBh
Y2thZ2VOYW1lICk7CgkJSURhdGFVdGlsLnB1dCggcGFja2FnZUNvbmZpZ0N1cnNvciwgIm1ldHJp
Y3NTZXJ2aWNlRnFuIiwgbWV0cmljc1NlcnZpY2VGcW4gKTsKCQlwYWNrYWdlQ29uZmlnQ3Vyc29y
LmRlc3Ryb3koKTsKCQlJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgInBhY2thZ2VDb25m
aWciLCBwYWNrYWdlQ29uZmlnICk7CgoJfSBjYXRjaCggSU9FeGNlcHRpb24gZSApIHsKCQlKb3Vy
bmFsTG9nZ2VyLmxvZyg0LCAgSm91cm5hbExvZ2dlci5GQUNfRkxPV19TVkMsIEpvdXJuYWxMb2dn
ZXIuRVJST1IsICJ3eC5wcm9tZXRoZXVzLmNvbmZpZyIsICJDb3VsZCBub3QgbG9hZCBjb25maWcg
ZmlsZSAnIiArIENPTkZJR19GSUxFX05BTUUgKyAiJyBmb3IgcGFja2FnZSAiICsgcGFja2FnZU5h
bWUgKyAiOiAiICsgZSApOwoJfQoJCglwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7Cn0KCQoJCg==
</value>
</Values>
